# fly.toml file generated for durable-workers on 2023-01-19T17:43:10-03:00

app = "durable-workers"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8001"

[experimental]
  auto_rollback = true

[processes]
  app = "run -A ./api/main.ts"
  workers = "run -A ./workers/main.ts"

[[services]]
  http_checks = []
  internal_port = 8001
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
